<?php

namespace Database\Seeders;

use App\Enums\ChallengeDifficulty;
use App\Models\Challenge;
use Illuminate\Database\Seeder;

class ChallengeSeeder extends Seeder
{
    public function run(): void
    {
        $challenges = [
            ['Cook a meal together', '🍳', ChallengeDifficulty::Medium],
            ['Watch the sunset', '🌅', ChallengeDifficulty::Easy],
            ['Dance to one song', '💃', ChallengeDifficulty::Easy],
            ['Give each other a five minute massage', '🤗', ChallengeDifficulty::Easy],
            ['No phones for one hour', '📵', ChallengeDifficulty::Medium],
            ['Write each other a love note', '💌', ChallengeDifficulty::Easy],
            ['Take a walk together', '🚶', ChallengeDifficulty::Easy],
            ['Bake dessert together', '🍰', ChallengeDifficulty::Medium],
            ['Play a board game', '🎲', ChallengeDifficulty::Easy],
            ['Watch a favourite movie', '🎬', ChallengeDifficulty::Easy],
            ['Watch the sunrise together', '🌄', ChallengeDifficulty::Hard],
            ['Cook breakfast in bed', '🥞', ChallengeDifficulty::Medium],
            ['Go stargazing', '⭐', ChallengeDifficulty::Easy],
            ['Have a picnic', '🧺', ChallengeDifficulty::Medium],
            ['Try a new restaurant', '🍽️', ChallengeDifficulty::Medium],
            ['Give a ten minute back rub', '💆', ChallengeDifficulty::Easy],
            ['Read to each other', '📖', ChallengeDifficulty::Easy],
            ['Take a bath together', '🛁', ChallengeDifficulty::Easy],
            ['Play a video game together', '🎮', ChallengeDifficulty::Easy],
            ['Go for a bike ride', '🚴', ChallengeDifficulty::Medium],
            ['Make a playlist for each other', '🎵', ChallengeDifficulty::Easy],
            ['Try a new recipe together', '👨‍🍳', ChallengeDifficulty::Medium],
            ['Have a candlelit dinner at home', '🕯️', ChallengeDifficulty::Medium],
            ['Write down three things you love about each other', '❤️', ChallengeDifficulty::Easy],
            ['Go to a farmers market', '🥦', ChallengeDifficulty::Easy],
            ['Take a day trip somewhere new', '🗺️', ChallengeDifficulty::Hard],
            ['Do yoga together', '🧘', ChallengeDifficulty::Medium],
            ['Go swimming together', '🏊', ChallengeDifficulty::Medium],
            ['Visit a museum or gallery', '🖼️', ChallengeDifficulty::Easy],
            ['Have a movie marathon', '🍿', ChallengeDifficulty::Easy],
            ['Make cocktails or mocktails together', '🍹', ChallengeDifficulty::Easy],
            ['Go to a comedy show', '😂', ChallengeDifficulty::Medium],
            ['Attend a live music event', '🎸', ChallengeDifficulty::Medium],
            ['Go hiking together', '🥾', ChallengeDifficulty::Hard],
            ['Have a spa night at home', '🧖', ChallengeDifficulty::Easy],
            ['Play card games', '🃏', ChallengeDifficulty::Easy],
            ['Do a puzzle together', '🧩', ChallengeDifficulty::Easy],
            ['Go bowling', '🎳', ChallengeDifficulty::Easy],
            ['Visit a botanical garden', '🌸', ChallengeDifficulty::Easy],
            ['Go to a drive-in movie', '🚗', ChallengeDifficulty::Medium],
            ['Make homemade pizza together', '🍕', ChallengeDifficulty::Medium],
            ['Have a karaoke night at home', '🎤', ChallengeDifficulty::Easy],
            ['Go ice skating', '⛸️', ChallengeDifficulty::Medium],
            ['Visit a local market', '🛍️', ChallengeDifficulty::Easy],
            ['Do a paint night together', '🎨', ChallengeDifficulty::Medium],
            ['Go to a wine or beer tasting', '🍷', ChallengeDifficulty::Medium],
            ['Have a bonfire together', '🔥', ChallengeDifficulty::Medium],
            ['Go kayaking or canoeing', '🛶', ChallengeDifficulty::Hard],
            ['Visit a theme park', '🎡', ChallengeDifficulty::Hard],
            ['Have a game night with friends', '🎉', ChallengeDifficulty::Medium],
            ['Go to a pottery class', '🏺', ChallengeDifficulty::Medium],
            ['Take a cooking class together', '👩‍🍳', ChallengeDifficulty::Hard],
            ['Go to a dance class', '💃', ChallengeDifficulty::Medium],
            ['Visit a zoo or aquarium', '🐠', ChallengeDifficulty::Easy],
            ['Go rock climbing', '🧗', ChallengeDifficulty::Hard],
            ['Have a themed dinner night', '🌍', ChallengeDifficulty::Medium],
            ['Make a scrapbook together', '📷', ChallengeDifficulty::Medium],
            ['Go to a sports event', '🏟️', ChallengeDifficulty::Medium],
            ['Plant something together', '🌱', ChallengeDifficulty::Easy],
            ['Go to an escape room', '🔐', ChallengeDifficulty::Medium],
            ['Have a silent dinner — no phones, no TV', '🤫', ChallengeDifficulty::Medium],
            ['Write a bucket list together', '📝', ChallengeDifficulty::Easy],
            ['Go to a flea market', '🛒', ChallengeDifficulty::Easy],
            ['Make sushi together', '🍣', ChallengeDifficulty::Hard],
            ['Go to a rooftop bar', '🌆', ChallengeDifficulty::Medium],
            ['Have a breakfast date', '☕', ChallengeDifficulty::Easy],
            ['Go to a comedy club', '🎭', ChallengeDifficulty::Medium],
            ['Do a random act of kindness together', '💛', ChallengeDifficulty::Easy],
            ['Go to a hot spring or spa', '♨️', ChallengeDifficulty::Hard],
            ['Make a time capsule together', '📦', ChallengeDifficulty::Medium],
            ['Go to a trivia night', '🧠', ChallengeDifficulty::Easy],
            ['Have a midnight snack together', '🌙', ChallengeDifficulty::Easy],
            ['Go to a flower market', '💐', ChallengeDifficulty::Easy],
            ['Make homemade ice cream', '🍦', ChallengeDifficulty::Medium],
            ['Go to a rooftop cinema', '🎥', ChallengeDifficulty::Medium],
            ['Have a lazy morning in bed', '🛏️', ChallengeDifficulty::Easy],
            ['Go to a night market', '🌃', ChallengeDifficulty::Easy],
            ['Make a vision board together', '✂️', ChallengeDifficulty::Medium],
            ['Go to a comedy podcast recording', '🎙️', ChallengeDifficulty::Hard],
            ['Have a fondue night', '🫕', ChallengeDifficulty::Medium],
            ['Go to a botanical garden at night', '🌿', ChallengeDifficulty::Medium],
            ['Make homemade candles together', '🕯️', ChallengeDifficulty::Medium],
            ['Go to a pottery market', '🏺', ChallengeDifficulty::Easy],
            ['Have a stargazing picnic', '🌠', ChallengeDifficulty::Medium],
            ['Go to a jazz bar', '🎷', ChallengeDifficulty::Medium],
            ['Make a photo album together', '📸', ChallengeDifficulty::Medium],
            ['Go to a rooftop garden', '🌻', ChallengeDifficulty::Easy],
            ['Have a board game tournament', '🏆', ChallengeDifficulty::Medium],
            ['Go to a street food festival', '🌮', ChallengeDifficulty::Easy],
            ['Make homemade pasta together', '🍝', ChallengeDifficulty::Medium],
            ['Go to a comedy festival', '😄', ChallengeDifficulty::Hard],
            ['Have a sunrise breakfast', '🌞', ChallengeDifficulty::Hard],
            ['Go to a night hike', '🌙', ChallengeDifficulty::Hard],
            ['Make a romantic playlist and slow dance', '🎶', ChallengeDifficulty::Easy],
            ['Go to a chocolate tasting', '🍫', ChallengeDifficulty::Easy],
            ['Have a backyard campfire', '🏕️', ChallengeDifficulty::Medium],
            ['Go to a rooftop yoga class', '🧘', ChallengeDifficulty::Hard],
            ['Make homemade bread together', '🍞', ChallengeDifficulty::Medium],
            ['Go to a sunset cruise', '⛵', ChallengeDifficulty::Hard],
            ['Have a couples yoga session at home', '🧘', ChallengeDifficulty::Medium],
        ];

        foreach ($challenges as $order => $challenge) {
            Challenge::create([
                'title' => $challenge[0],
                'description' => null,
                'emoji' => $challenge[1],
                'difficulty' => $challenge[2],
                'active' => true,
                'display_order' => $order + 1,
            ]);
        }
    }
}
