<?php

namespace Database\Seeders;

use App\Enums\IntimacyGameCategory;
use App\Enums\IntimacyGameIntensity;
use App\Models\IntimacyGame;
use Illuminate\Database\Seeder;

class IntimacyGameSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->games() as $index => $game) {
            IntimacyGame::firstOrCreate(
                ['slug' => $game['slug']],
                array_merge($game, ['display_order' => $game['display_order'] ?? $index + 1]),
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function games(): array
    {
        return [
            [
                'title' => 'Truth or Dare: After Dark',
                'slug' => 'truth-or-dare-after-dark',
                'emoji' => '🎲',
                'tagline' => 'Flirty truths and playful dares, only for two.',
                'description' => 'A grown-up spin on the classic. Take turns picking truth or dare and see where the night leads you.',
                'how_to_play' => 'Take turns choosing truth or dare. If you pick truth, tap a truth card and answer honestly. If you pick dare, tap a dare card and act it out together. No judgement, only laughs and sparks.',
                'players' => 2,
                'estimated_minutes' => 30,
                'intensity' => IntimacyGameIntensity::Spicy->value,
                'category' => IntimacyGameCategory::Game->value,
                'display_order' => 1,
                'prompts' => [
                    'Truth: What is the sexiest thing I have ever done for you without realising it?',
                    'Truth: What is a fantasy you have never shared with anyone?',
                    'Truth: Where do you love being kissed the most?',
                    'Dare: Whisper what you want to do next in my ear.',
                    'Dare: Give me a two-minute slow massage — anywhere you choose.',
                    'Dare: Undress one item of my clothing using only your teeth.',
                    'Truth: What is one thing you would love us to try more often?',
                    'Dare: Make eye contact for one full minute without breaking it.',
                    'Truth: What outfit of mine drives you wild?',
                    'Dare: Pick a song and dance for me for its first minute.',
                ],
            ],
            [
                'title' => 'Kiss, Touch, Tease',
                'slug' => 'kiss-touch-tease',
                'emoji' => '💋',
                'tagline' => 'Roll a card, obey the card.',
                'description' => 'A tender warm-up game that keeps you present with each other. Every card is a soft invitation.',
                'how_to_play' => 'Shuffle the deck and take turns drawing. Each card tells you exactly what to do next. Go slowly. Enjoy every second.',
                'players' => 2,
                'estimated_minutes' => 15,
                'intensity' => IntimacyGameIntensity::Flirty->value,
                'category' => IntimacyGameCategory::Game->value,
                'display_order' => 2,
                'prompts' => [
                    'Kiss my neck for ten seconds.',
                    'Trace a heart on my back with one finger.',
                    'Whisper three things you love about my body.',
                    'Kiss me somewhere you have never kissed me before.',
                    'Hold my hand and stare into my eyes for thirty seconds.',
                    'Tease me by kissing everywhere except my lips for a full minute.',
                    'Slowly take off my socks — make it romantic.',
                    'Give me a five-second kiss with no touching anywhere else.',
                    'Run your fingertips down my arm as slowly as you can.',
                    'Kiss my forehead, then my nose, then my lips.',
                ],
            ],
            [
                'title' => 'Would You Rather: Bedroom Edition',
                'slug' => 'would-you-rather-bedroom-edition',
                'emoji' => '🤔',
                'tagline' => 'Playful choices that unlock new fantasies.',
                'description' => 'Learn something new about each other with every question. Some are silly, some are steamy, all are safe.',
                'how_to_play' => 'Take turns reading a prompt aloud and give your honest answer. Ask each other why. Consider trying tonight’s favourites right after.',
                'players' => 2,
                'estimated_minutes' => 20,
                'intensity' => IntimacyGameIntensity::Flirty->value,
                'category' => IntimacyGameCategory::Truth->value,
                'display_order' => 3,
                'prompts' => [
                    'Would you rather be teased all evening or surprised in five minutes?',
                    'Would you rather give a long massage or receive one?',
                    'Would you rather try something new tonight or perfect a favourite?',
                    'Would you rather have candles or fairy lights?',
                    'Would you rather be told exactly what to do or take the lead?',
                    'Would you rather share a bath first or straight after?',
                    'Would you rather slow music or complete silence?',
                    'Would you rather send me a spicy text at lunch or a love note in my bag?',
                ],
            ],
            [
                'title' => 'Roleplay Roulette',
                'slug' => 'roleplay-roulette',
                'emoji' => '🎭',
                'tagline' => 'Step into someone new for a night.',
                'description' => 'Pick a scenario together and commit to the story. Playful characters make new memories.',
                'how_to_play' => 'Choose a scenario together. Decide who plays which role. Agree on a soft safe word. Then step into character and see where the story takes you.',
                'players' => 2,
                'estimated_minutes' => 45,
                'intensity' => IntimacyGameIntensity::Wild->value,
                'category' => IntimacyGameCategory::Roleplay->value,
                'display_order' => 4,
                'prompts' => [
                    'Strangers meeting at a hotel bar for the very first time.',
                    'A late-night massage appointment that turns romantic.',
                    'Reunited long-distance lovers after months apart.',
                    'A photographer and their muse on a private shoot.',
                    'A dance instructor giving a very private lesson.',
                    'A rock star and a very lucky guest backstage.',
                    'Two rivals who finally admit they have chemistry.',
                    'Housemates snowed in with only one bed left.',
                ],
            ],
            [
                'title' => 'Sensory Escape',
                'slug' => 'sensory-escape',
                'emoji' => '🪶',
                'tagline' => 'One sense at a time. All of them together.',
                'description' => 'Heighten every touch by taking sight away. A soft blindfold turns the smallest touch into a firework.',
                'how_to_play' => 'One partner puts on a blindfold. The other guides them through five sensations, one at a time — taste, smell, sound, temperature, touch. Swap after.',
                'players' => 2,
                'estimated_minutes' => 25,
                'intensity' => IntimacyGameIntensity::Spicy->value,
                'category' => IntimacyGameCategory::Game->value,
                'display_order' => 5,
                'prompts' => [
                    'Taste: a strawberry, a square of chocolate, a sip of wine.',
                    'Smell: perfume on their wrist, a favourite candle.',
                    'Sound: whisper a favourite memory into their ear.',
                    'Temperature: an ice cube slowly traced along the collarbone.',
                    'Touch: a feather down their arm, then fingertips down their back.',
                    'Taste: honey on the fingertip.',
                    'Sound: play the song from your first dance.',
                    'Touch: a silk scarf trailed across the skin.',
                ],
            ],
            [
                'title' => 'Strip Card Draw',
                'slug' => 'strip-card-draw',
                'emoji' => '🃏',
                'tagline' => 'The deck decides how bold you get.',
                'description' => 'A cheeky spin on card games. Every draw either takes something off, adds a kiss, or unlocks a dare.',
                'how_to_play' => 'Grab any deck of cards. Reds = they lose a layer. Blacks = you lose a layer. Face cards = a kiss of your choice. Aces = a wild dare. Play until you both feel the sparks fly.',
                'players' => 2,
                'estimated_minutes' => 20,
                'intensity' => IntimacyGameIntensity::Wild->value,
                'category' => IntimacyGameCategory::Dare->value,
                'display_order' => 6,
                'prompts' => [
                    'Ace of hearts: kiss anywhere you have never kissed before.',
                    'King of diamonds: a slow thirty-second neck kiss.',
                    'Queen of clubs: a two-minute back massage.',
                    'Jack of spades: whisper what you want to happen next.',
                    'Any red 10: swap places and lead for the next round.',
                    'Any black 7: dance together to one full song, no talking.',
                ],
            ],
            [
                'title' => 'Fantasy Jar',
                'slug' => 'fantasy-jar',
                'emoji' => '💭',
                'tagline' => 'Whisper it, fold it, live it later.',
                'description' => 'Fill a shared jar with wishes and pick one on any date night. A little ritual you build together over time.',
                'how_to_play' => 'Each partner writes down three fantasies on separate slips. Fold and add them to your Fantasy Jar. Once a week, pick one together and bring it to life.',
                'players' => 2,
                'estimated_minutes' => 15,
                'intensity' => IntimacyGameIntensity::Spicy->value,
                'category' => IntimacyGameCategory::Game->value,
                'display_order' => 7,
                'prompts' => [
                    'A night in a hotel room, no phones allowed.',
                    'Breakfast in bed followed by a very slow morning.',
                    'A dance in the living room in nothing but underwear.',
                    'A candlelit bath with wine and playlist ready.',
                    'A surprise handwritten letter left on the pillow.',
                    'Try one new touch tonight and tell me if you love it.',
                ],
            ],
            [
                'title' => 'Massage Marathon',
                'slug' => 'massage-marathon',
                'emoji' => '💆',
                'tagline' => 'Twenty minutes of pure attention.',
                'description' => 'A guided massage journey that swaps roles halfway. Slow, tender and deeply connecting.',
                'how_to_play' => 'Dim the lights, pick a soft playlist, warm the oil. Massage your partner for ten minutes following the prompts. Then swap and let them do the same for you.',
                'players' => 2,
                'estimated_minutes' => 20,
                'intensity' => IntimacyGameIntensity::Flirty->value,
                'category' => IntimacyGameCategory::Game->value,
                'display_order' => 8,
                'prompts' => [
                    'Start at the shoulders with long, slow strokes for two minutes.',
                    'Move to the arms and hands, massaging each finger.',
                    'Return to the upper back and use gentle circular pressure.',
                    'Trace slow, deliberate lines down the spine.',
                    'Massage the lower back with the palms of your hands.',
                    'Finish with a full body sweep from shoulders to ankles.',
                ],
            ],
            [
                'title' => 'Dare Deck Draw',
                'slug' => 'dare-deck-draw',
                'emoji' => '🔥',
                'tagline' => 'Draw one. No backing out.',
                'description' => 'For nights when you want the game to make the decisions. Bold, cheeky and just the right amount of wild.',
                'how_to_play' => 'Take turns tapping the deck. Whatever you draw, you commit to. Skip one card per person per night — use it wisely.',
                'players' => 2,
                'estimated_minutes' => 20,
                'intensity' => IntimacyGameIntensity::Wild->value,
                'category' => IntimacyGameCategory::Dare->value,
                'display_order' => 9,
                'prompts' => [
                    'Undress your partner one layer at a time — no hands allowed for the first item.',
                    'Give a two-minute kiss without touching each other anywhere else.',
                    'Whisper your favourite memory of us in explicit detail.',
                    'Feed each other something sweet, blindfolded.',
                    'Trade three compliments about each other’s body.',
                    'Slow dance in your underwear to a song they choose.',
                    'Send a spicy voice note to your partner from the next room.',
                ],
            ],
            [
                'title' => 'Never Have We Ever… Together',
                'slug' => 'never-have-we-ever-together',
                'emoji' => '🥂',
                'tagline' => 'Discover firsts you still want to share.',
                'description' => 'A romantic twist on the classic — a chance to make new firsts a shared bucket list.',
                'how_to_play' => 'Take turns reading a prompt. If you have never done it together, one of you writes it on a new list for future nights. If you have, share your favourite memory of it.',
                'players' => 2,
                'estimated_minutes' => 25,
                'intensity' => IntimacyGameIntensity::Flirty->value,
                'category' => IntimacyGameCategory::Truth->value,
                'display_order' => 10,
                'prompts' => [
                    'Never have we ever kissed in the rain.',
                    'Never have we ever spent a whole day in bed.',
                    'Never have we ever written each other a love letter.',
                    'Never have we ever watched the sunrise together.',
                    'Never have we ever cooked dinner naked (aprons optional).',
                    'Never have we ever recreated our first date.',
                    'Never have we ever taken a spontaneous overnight trip.',
                ],
            ],
        ];
    }
}
